version: '3.8'
services:
  zk1:
    container_name: zk1
    hostname: zk1
    image: zookeeper:3.8.1
    ports:
      - 21811:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181
    healthcheck:
      test: "nc -z localhost 2181"
      start_period: 30s
      timeout: 5s
      interval: 10s
      retries: 3
    networks:
      - zookeeper_net

  zk2:
    container_name: zk2
    hostname: zk2
    image: zookeeper:3.8.1
    restart: always
    ports:
      - 22182:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181
    networks:
      - zookeeper_net

  mysql1:
    image: mysql_mysync_base:mysql
    hostname: mysql1
    ports:
      - '13306:3306'
    environment:
      MYSQL_SERVER_ID: 1
      MYSQL_ADMIN_USER: admin
      MYSQL_ADMIN_PASSWORD: admin_pwd
      MYSQL_MASTER: ''
      MYSYNC_FAILOVER: true
      MYSYNC_FAILOVER_DELAY: 10s
      MYSYNC_FAILOVER_COOLDOWN: 10s
      MYSYNC_INACTIVATION_DELAY: 10s
      ZK_SERVERS: zk1:2181, zk2:2181
      MYSQL_PORT: 3306
      MYSYNC_DISABLE_REPLICATION_ON_MAINT: "true"
      MYSYNC_SEMISYNC:
      MYSYNC_CRITICAL_DISK_USAGE:
      MYSYNC_KEEP_SUPER_WRITABLE_ON_CRITICAL_DISK_USAGE:
      MYSYNC_WAIT_FOR_SLAVE_COUNT:
      MYSYNC_STREAM_FROM_REASONABLE_LAG:
      MYSYNC_RESETUP_CRASHED_HOSTS:
      MYSYNC_REPLICATION_REPAIR_AGGRESSIVE_MODE:
      MYSYNC_SET_RO_TIMEOUT:
    healthcheck:
      test: "mysql --user=admin --password=admin_pwd -e 'SELECT 1'"
      start_period: 30s
      timeout: 5s
      interval: 10s
      retries: 3
    volumes:
      - ./mysync_compose.yaml:/var/lib/dist/mysql/mysync.yaml
    depends_on:
      zk1:
        condition: service_healthy
    networks:
      - zookeeper_net

  mysql2:
    image: mysql_mysync_base:mysql
    hostname: mysql2
    ports:
      - '23306:3306'
    privileged: true
    environment:
      MYSQL_SERVER_ID: 2
      MYSQL_ADMIN_USER: admin
      MYSQL_ADMIN_PASSWORD: admin_pwd
      MYSQL_MASTER: mysql1
      MYSYNC_FAILOVER: true
      MYSYNC_FAILOVER_DELAY: 10s
      MYSYNC_FAILOVER_COOLDOWN: 10s
      MYSYNC_INACTIVATION_DELAY: 10s
      ZK_SERVERS: zk1:2181, zk2:2181
      MYSQL_PORT: 3306
      MYSYNC_DISABLE_REPLICATION_ON_MAINT: "true"
      MYSYNC_SEMISYNC:
      MYSYNC_CRITICAL_DISK_USAGE:
      MYSYNC_KEEP_SUPER_WRITABLE_ON_CRITICAL_DISK_USAGE:
      MYSYNC_WAIT_FOR_SLAVE_COUNT:
      MYSYNC_STREAM_FROM_REASONABLE_LAG:
      MYSYNC_RESETUP_CRASHED_HOSTS:
      MYSYNC_REPLICATION_REPAIR_AGGRESSIVE_MODE:
      MYSYNC_SET_RO_TIMEOUT:
    depends_on:
      mysql1:
        condition: service_healthy
    volumes:
      - ./mysync_compose.yaml:/var/lib/dist/mysql/mysync.yaml
    networks:
      - zookeeper_net

  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    restart: unless-stopped
    ports:
      - 9080:9000/tcp
    environment:
      ########## Server ##########

      # Tells the HTTP server which port to bind to. To disable HTTP set this variable to disabled.
      HTTP_PORT: 9000

      # If set, HTTPS server will bind to this port.
      #HTTPS_PORT:

      # The path to the keystore containing the private key and certificate, if not provided generates a keystore for
      # you.
      #SSL_KEYSTORE_PATH: ''

      # The password to the keystore, defaults to a blank password.
      #SSL_KEYSTORE_PASSWORD: ''

      # The key store type.
      #SSL_KEYSTORE_TYPE: JKS

      # Sets session inactivity timeout for users. This value is in milliseconds.
      #SESSION_TIMEOUT_MILLIS: 900000

      # Secret key for Play Framework - used for signing session cookies and CSRF tokens. Defaults to 64 random
      # characters generated from /dev/urandom.
      #SECRET_KEY: ''

      # If set, ZooNavigator will use this value as a default connection string and skip the connect form,
      # automatically connecting to listed ZooKeeper servers.
      AUTO_CONNECT_CONNECTION_STRING: 'zk1:2181,zk2:2181'
    networks:
      - zookeeper_net

networks:
  zookeeper_net:
    driver: bridge
#  mysync_net:
#    driver: bridge

volumes:
  mysql_data: